version: '3.7'

services:
  puppet:
    environment:
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-false}

  # NOTE: if this service changes, global shared definition should be updated
  # https://github.com/puppetlabs/pupperware/blob/main/gem/lib/pupperware/compose-services/puppetdb.yml
  puppetdb:
    hostname: puppetdb
    image: ${PUPPETDB_IMAGE:-puppet/puppetdb}
    environment:
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-false}
      - CERTNAME=puppetdb
      # NOTE: Java follows RFC 2818 stating when SAN is provided, it's authoritative / Subject should be ignored
      - DNS_ALT_NAMES=${PUPPETDB_DNS_ALT_NAMES:-puppetdb}
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETSERVER_PORT=8140
      - PUPPETDB_POSTGRES_HOSTNAME=postgres
      - PUPPETDB_POSTGRES_PORT=5432
      - PUPPETDB_USER=puppetdb
      - PUPPETDB_PASSWORD=puppetdb
    volumes:
      - puppetdb:/opt/puppetlabs/server/data/puppetdb
    ports:
      - 8080
      - 8081

networks:
  default:
    name: puppetdb_test

volumes:
  puppetdb:
