---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "puppetdb.fullname" . }}
  labels:
    app: {{ template "puppetdb.name" . }}
    chart: {{ template "puppetdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: {{ template "puppetdb.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "puppetdb.fullname" . }}
  labels:
    app: {{ template "puppetdb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: {{.Values.volumes.puppetdbvar.storageClass}}
  resources:
    requests:
      storage: {{.Values.volumes.puppetdbvar.size}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "puppetdb.fullname" . }}
  labels:
    app: {{ template "puppetdb.name" . }}
    chart: {{ template "puppetdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "puppetdb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "puppetdb.name" . }}
        release: {{ .Release.Name }}      
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{.Values.imageRegistry}}/puppet/puppetdb:{{.Values.dockerTag}}
        imagePullPolicy: {{.Values.pullPolicy}}
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        # TODO: update this properly
        volumeMounts:
        - mountPath: /etc/puppetlabs/puppetdb/conf.d
          name: config
        - mountPath: /etc/puppetlabs/puppetdb/ssl
          name: ssl
        - mountPath: /opt/puppetlabs/server/data/puppetdb
          name: vardir
      volumes:
      - name: config
        configMap:
          name: {{ template "puppetdb.fullname" . }}
          items:
          - key: pdb-ini
            path: pdb.ini
          - key: logback
            path: logback.xml
      - name: ssl
        emptyDir: {}
      - name: vardir
        persistentVolumeClaim:
          claimName: {{ template "puppetdb.fullname" . }}
