---
apiVersion: v1
kind: Service
metadata:
  name: puppetdb
  labels:
    app: puppetdb
spec:
  ports:
  - port: 8080
    name: web
  - port: 8081
    name: webs
  selector:
    app: puppetdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppetdb-var
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetdb-deployment
  labels:
    app: puppetdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puppetdb
  template:
    metadata:
      labels:
        app: puppetdb
    spec:
      containers:
      - name: puppetdb
        image: 10.100.7.236:80/puppet/puppetdb:latest
        ports:
        - containerPort: 8080
        - containerPort: 8081
        #TODO: all this stuff is wrong now
        volumeMounts:
        - mountPath: /etc/puppetlabs/puppetdb/conf.d
          name: config
        - mountPath: /etc/puppetlabs/puppetdb/ssl
          name: ssl
        - mountPath: /opt/puppetlabs/server/data/puppetdb
          name: vardir
      volumes:
      #TODO: this doesn't make sense in containers anymore really
      - name: config
        configMap:
          name: puppetdb-config
          items:
          - key: pdb-ini
            path: pdb.ini
          - key: logback
            path: logback.xml
      - name: ssl
        emptyDir: {}
      - name: vardir
        persistentVolumeClaim:
          claimName: puppetdb-var
