name: Docs test

on:
  pull_request:
    paths:
      - 'documentation/**/*'
    
jobs:
  run-dita:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize
      uses: actions/checkout@v2

    - name: Docs test
      uses: dita-ot/dita-ot-action@master
      with:
        build: |
          dita -i documentation/puppetdb.ditamap -o out -f html5 --processing-mode=strict